TWDNKY=false
ADVANCED_LAB=false
SKILL_LEVEL=15
SEEKER_OF_SHADOWS=false
PHYSICIAN_ORDINATOR=
ALCHEMIST=0
POISONER_ORDINATOR=false
PHYSICIAN_BASE_GAME=false
POISONER_BASE_GAME=false
BENEFACTOR=false
ALCHEMY_MASTERY=0
TOTAL_ENCHANTMENT_BONUS=0
